# enable zmk studio for realtime keymap updates
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
# Mouse enable
CONFIG_ZMK_POINTING=y
# Sleep configuration
CONFIG_ZMK_SLEEP=y
# 30 seconds
CONFIG_ZMK_IDLE_TIMEOUT=30000
# 1 hour
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000
